FROM ruby:3.4.4

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev wget && rm -rf /var/lib/apt/lists/*

RUN wget https://github.com/anycable/anycable-go/releases/download/v1.4.0/anycable-go-linux-amd64 -O /usr/local/bin/anycable-go && \
    chmod +x /usr/local/bin/anycable-go

WORKDIR /app

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

EXPOSE 3001
CMD ["anycable-go", "--host=0.0.0.0", "--port=3001"]
