# AnyCable configuration
default: &default # AnyCable RPC server settings
  rpc_host: "127.0.0.1:50051"

  # Redis settings for pub/sub
  redis_url: <%= ENV.fetch("REDIS_URL", "redis://localhost:6379/1") %>
  redis_channel: "__anycable__"

  # Broadcasting settings
  broadcast_adapter: redis

  # Connection settings
  max_connection_age: 3600 # 1 hour
  disconnect_timeout: 5

  # Logging
  log_level: info
  log_file: log/anycable.log

  # Performance settings
  rpc_pool_size: 30
  rpc_pool_keep_alive: 30

development:
  <<: *default
  log_level: debug
  rpc_host: "127.0.0.1:50051"

test:
  <<: *default
  redis_url: "redis://localhost:6379/2"
  log_level: fatal

production:
  <<: *default
  rpc_host: "0.0.0.0:50051"
  redis_url: <%= ENV.fetch("REDIS_URL", "redis://localhost:6379/1") %>
  log_level: info

  # Production optimizations
  rpc_pool_size: 50
  max_connection_age: 1800

  # Enable metrics
  metrics_log: true
  metrics_log_interval: 15

  # Server settings
  server_command: "anycable-go --host=0.0.0.0 --port=8081"
